services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app  # monta a raiz do projeto no container
    env_file:
      - .env
    command: sh -c "uvicorn app.main:app --host 0.0.0.0"
    depends_on:
      - postgresql

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - biblioteca_db_data:/var/lib/postgresql/data

  postgresql-test:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - biblioteca_test_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - postgresql

volumes:
  biblioteca_db_data:
  biblioteca_test_db_data:
