"""GrupoPolitica e Permissao

Revision ID: 857ee0b93369
Revises: a19aa8383643
Create Date: 2025-02-04 14:01:38.703258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '857ee0b93369'
down_revision: Union[str, None] = 'a19aa8383643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
