"""Criando todas as tabelas

Revision ID: a19aa8383643
Revises: 
Create Date: 2025-02-03 15:33:35.923203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a19aa8383643'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('editora', sa.String(length=100), nullable=True),
    sa.Column('ano_publicacao', sa.Integer(), nullable=True),
    sa.Column('numero_paginas', sa.Integer(), nullable=True),
    sa.Column('quantidade_disponivel', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('endereco_completo', sa.String(length=200), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('grupo_politica', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emprestimo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('data_devolucao', sa.DateTime(), nullable=True),
    sa.Column('numero_renovacoes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['livro_id'], ['livro.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimo')
    op.drop_table('usuario')
    op.drop_table('livro')
    # ### end Alembic commands ###
